### ISSUE TITLE
Implement a more professional cli interface

### ISSUE THREAD

**Issue by jk** [rips/librips-php#7]
Replace the homegrown implementation of a CLI interface with the proven work of something like the [symfony/console](http://symfony.com/doc/current/components/console.html) project. It gives you a lot of neat features for free, like a proper `--help` screen, argument parsing, etc.

**Comment by rips-hb** [comment]
Hi. This is a misunderstanding that affects all 3 issues. The script is not intended to be actually used in production, it is just a code example that demonstrates how the lib can be used. As such it is limited to the absolute necessary functionality.

A real command line interface is planned, there is no fixed release date yet though. I will close the issues here, because it will be a different project and not directly integrated into this lib. When we create it you can certainly expect proper CLI behaviour and a phar archive though.
